import { SOURCE_PRIORITY } from './schema.js'

function extractDeepAnalysis(summary) {
  const start = 'HEALTH_CONNECT_DEEP_ANALYSIS_JSON_START'
  const end = 'HEALTH_CONNECT_DEEP_ANALYSIS_JSON_END'
  const startIndex = summary.indexOf(start)
  const endIndex = summary.indexOf(end)
  if (startIndex === -1 || endIndex === -1 || endIndex <= startIndex) return null

  const raw = summary.slice(startIndex + start.length, endIndex).trim()
  try {
    return JSON.parse(raw)
  } catch {
    return null
  }
}

function ensureMetric(inventory, file) {
  if (!inventory.metrics[file.name]) inventory.metrics[file.name] = { type: file.type }
  return inventory.metrics[file.name]
}

/**
 * Builds a structured, deterministic data pack from parsed files.
 * This helps the LLM avoid "guessing" and provides hard numbers.
 */
export function buildStructuredDataPack(parsedFiles) {
  const inventory = {
    files: [],
    metrics: {},
    dateRange: [null, null],
    warnings: [],
  }

  parsedFiles.forEach(file => {
    inventory.files.push({
      name: file.name,
      type: file.type,
      size: (file.size / 1024).toFixed(1) + ' KB'
    })

    // Heuristic extraction from the "summary" text generated by fileParser.js
    // We look for patterns like "Total rows: 123", "Steps: avg ~5000", etc.
    const summary = file.summary || ''
    const deepAnalysis = extractDeepAnalysis(summary)
    
    // Extract row counts
    const rowMatch = summary.match(/Total rows: (\d+)/)
    if (rowMatch) {
      const count = parseInt(rowMatch[1])
      inventory.metrics[file.name] = { rows: count, type: file.type }
    }
    if (deepAnalysis) {
      inventory.metrics[file.name] = {
        ...(inventory.metrics[file.name] || { type: file.type }),
        isHealthConnect: true,
        deepAnalysis,
      }
    }

    // Look for specific metrics and averages
    const metricsLines = summary.split('\n').filter(l => l.includes('avg ~'))
    metricsLines.forEach(line => {
      const match = line.match(/- (.*?): avg ~([\d.]+)/)
      if (match) {
        const name = match[1].trim()
        const avg = parseFloat(match[2])
        const metric = ensureMetric(inventory, file)
        if (!metric.details) metric.details = {}
        metric.details[name] = avg
      }
    })

    // Detect if this is a Health Connect DB
    if (summary.includes('HEALTH CONNECT EXPORT') || summary.includes('tablesFound')) {
      ensureMetric(inventory, file).isHealthConnect = true
    }
  })

  // Build the final string for the LLM
  let output = '=== DETERMINISTIC DATA INVENTORY ===\n'
  inventory.files.forEach(f => {
    output += `- ${f.name} (${f.type}, ${f.size})\n`
    const stats = inventory.metrics[f.name]
    if (stats) {
      if (stats.rows != null) output += `  * Records: ${stats.rows}\n`
      if (stats.deepAnalysis) {
        const deep = stats.deepAnalysis
        output += `  * Health Connect Deep Analysis: ${deep.detected_tables?.length || 0} native tables detected\n`
        if (deep.heart_rate) {
          output += `  * HR samples: ${deep.heart_rate.samples}; days: ${deep.heart_rate.days}; elevated episodes: ${deep.heart_rate.elevated_episodes?.length || 0}\n`
        }
        if (deep.sleep) output += `  * Sleep nights after dedupe: ${deep.sleep.nights}\n`
      }
      if (stats.details) {
        Object.entries(stats.details).forEach(([m, v]) => {
          output += `  * ${m}: sample average ${v}\n`
        })
      }
    }
  })

  output += '\n=== DATA QUALITY & SOURCE PRIORITY ===\n'
  Object.entries(SOURCE_PRIORITY).forEach(([metric, sources]) => {
    output += `- ${metric} priority: ${sources.join(' > ')}\n`
  })

  output += '\n=== RAW SUMMARIES ===\n'
  parsedFiles.forEach(f => {
    output += `\n--- Summary of ${f.name} ---\n${f.summary}\n`
  })

  const deepAnalyses = Object.entries(inventory.metrics)
    .filter(([, stats]) => stats.deepAnalysis)
    .map(([name, stats]) => ({ file: name, analysis: stats.deepAnalysis }))

  if (deepAnalyses.length) {
    output += '\n=== STRUCTURED HEALTH CONNECT DEEP ANALYSIS JSON ===\n'
    output += JSON.stringify(deepAnalyses, null, 2)
    output += '\n'
  }

  return output
}
