import { SOURCE_PRIORITY } from './schema.js'

/**
 * Builds a structured, deterministic data pack from parsed files.
 * This helps the LLM avoid "guessing" and provides hard numbers.
 */
export function buildStructuredDataPack(parsedFiles) {
  const inventory = {
    files: [],
    metrics: {},
    dateRange: [null, null],
    warnings: [],
  }

  parsedFiles.forEach(file => {
    inventory.files.push({
      name: file.name,
      type: file.type,
      size: (file.size / 1024).toFixed(1) + ' KB'
    })

    // Heuristic extraction from the "summary" text generated by fileParser.js
    // We look for patterns like "Total rows: 123", "Steps: avg ~5000", etc.
    const summary = file.summary || ''
    
    // Extract row counts
    const rowMatch = summary.match(/Total rows: (\d+)/)
    if (rowMatch) {
      const count = parseInt(rowMatch[1])
      inventory.metrics[file.name] = { rows: count, type: file.type }
    }

    // Look for specific metrics and averages
    const metricsLines = summary.split('\n').filter(l => l.includes('avg ~'))
    metricsLines.forEach(line => {
      const match = line.match(/- (.*?): avg ~([\d.]+)/)
      if (match) {
        const name = match[1].trim()
        const avg = parseFloat(match[2])
        if (!inventory.metrics[file.name].details) inventory.metrics[file.name].details = {}
        inventory.metrics[file.name].details[name] = avg
      }
    })

    // Detect if this is a Health Connect DB
    if (summary.includes('HEALTH CONNECT EXPORT') || summary.includes('tablesFound')) {
      inventory.metrics[file.name].isHealthConnect = true
    }
  })

  // Build the final string for the LLM
  let output = '=== DETERMINISTIC DATA INVENTORY ===\n'
  inventory.files.forEach(f => {
    output += `- ${f.name} (${f.type}, ${f.size})\n`
    const stats = inventory.metrics[f.name]
    if (stats) {
      output += `  * Records: ${stats.rows}\n`
      if (stats.details) {
        Object.entries(stats.details).forEach(([m, v]) => {
          output += `  * ${m}: sample average ${v}\n`
        })
      }
    }
  })

  output += '\n=== DATA QUALITY & SOURCE PRIORITY ===\n'
  Object.entries(SOURCE_PRIORITY).forEach(([metric, sources]) => {
    output += `- ${metric} priority: ${sources.join(' > ')}\n`
  })

  output += '\n=== RAW SUMMARIES ===\n'
  parsedFiles.forEach(f => {
    output += `\n--- Summary of ${f.name} ---\n${f.summary}\n`
  })

  return output
}
