import { useState, useMemo } from 'react'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'

export default function AnalysisView({ result, streaming }) {
  const [copied, setStreaming] = useState(false)

  const handleCopy = () => {
    navigator.clipboard.writeText(result)
    setStreaming(true)
    setTimeout(() => setStreaming(false), 2000)
  }

  const handleDownload = (type = 'md') => {
    let blob, filename
    if (type === 'md') {
      blob = new Blob([result], { type: 'text/markdown' })
      filename = `health-analysis-${new Date().toISOString().split('T')[0]}.md`
    } else {
      const html = `
        <!DOCTYPE html>
        <html>
        <head>
          <meta charset="utf-8">
          <title>HealthLens Analysis</title>
          <style>
            @media print {
              body { margin: 0; padding: 2cm; }
              .no-print { display: none; }
              .page-break { page-break-before: always; }
              .disclaimer { border: 2px solid #92400e !important; }
            }
            body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; line-height: 1.6; max-width: 850px; margin: 40px auto; padding: 20px; color: #1e293b; background: #fff; }
            h1, h2, h3 { color: #0f172a; margin-top: 1.5em; margin-bottom: 0.5em; }
            h1 { font-size: 2.25rem; border-bottom: 2px solid #e2e8f0; padding-bottom: 0.5em; }
            h2 { font-size: 1.5rem; border-bottom: 1px solid #e2e8f0; padding-bottom: 0.3em; }
            h3 { font-size: 1.25rem; }
            p { margin-bottom: 1em; }
            ul, ol { margin-bottom: 1em; padding-left: 1.5em; }
            li { margin-bottom: 0.5em; }
            code { background: #f1f5f9; padding: 2px 4px; border-radius: 4px; font-family: monospace; font-size: 0.9em; }
            blockquote { border-left: 4px solid #cbd5e1; margin: 1.5em 0; padding: 0.5em 1.5em; color: #475569; background: #f8fafc; font-style: italic; }
            table { width: 100%; border-collapse: collapse; margin: 1.5em 0; }
            th, td { border: 1px solid #e2e8f0; padding: 12px; text-align: left; }
            th { background: #f8fafc; font-weight: 600; }
            .header-info { display: flex; justify-content: space-between; align-items: flex-end; margin-bottom: 2em; color: #64748b; font-size: 0.875rem; }
            .disclaimer { background: #fffbeb; border: 1px solid #fef3c7; padding: 20px; border-radius: 12px; font-size: 0.9rem; color: #92400e; margin-top: 3em; }
            .gp-section { background: #f0f9ff; border: 1px solid #bae6fd; padding: 20px; border-radius: 12px; margin: 2em 0; }
            .gp-section h3 { margin-top: 0; color: #0369a1; }
          </style>
        </head>
        <body>
          <div class="header-info">
            <span>HealthLens Personal Analysis</span>
            <span>Generated: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}</span>
          </div>
          <h1>Health Data Analysis Report</h1>
          ${result.replace(/\n/g, '<br/>')}
          <div class="disclaimer">
            <strong>⚕️ MEDICAL DISCLAIMER:</strong> This analysis is generated by AI for personal reflection and data organization only. It is NOT a medical diagnosis, clinical opinion, or professional health advice. Please discuss any findings, symptoms, or concerns with your GP or a qualified health professional.
          </div>
          <div class="no-print" style="margin-top: 20px; text-align: center;">
            <button onclick="window.print()" style="background: #0f172a; color: white; border: none; padding: 10px 20px; border-radius: 8px; cursor: pointer; font-weight: 600;">Print Report / Save as PDF</button>
          </div>
        </body>
        </html>
      `
      blob = new Blob([html], { type: 'text/html' })
      filename = `health-analysis-${new Date().toISOString().split('T')[0]}.html`
    }
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="bg-ink-soft border border-slate-border rounded-2xl overflow-hidden">
      {/* Toolbar */}
      <div className="flex items-center justify-between px-5 py-3 border-b border-slate-border bg-ink">
        <div className="flex items-center gap-2">
          {streaming ? (
            <>
              <div className="w-2 h-2 rounded-full bg-jade animate-pulse-slow"></div>
              <span className="text-jade text-xs font-mono">Analysing...</span>
            </>
          ) : (
            <>
              <div className="w-2 h-2 rounded-full bg-jade"></div>
              <span className="text-jade text-xs font-mono">Analysis complete</span>
            </>
          )}
        </div>
        {!streaming && result && (
          <div className="flex gap-2">
            <button
              onClick={handleCopy}
              className="text-xs text-slate-ui hover:text-white border border-slate-border hover:border-jade/40 px-2.5 py-1 rounded-lg transition-all"
            >
              {copied ? 'Copied!' : 'Copy'}
            </button>
            <div className="flex rounded-lg overflow-hidden border border-slate-border">
              <button
                onClick={() => handleDownload('md')}
                className="text-xs text-slate-ui hover:text-white border-r border-slate-border hover:bg-white/5 px-2.5 py-1 transition-all"
              >
                .MD
              </button>
              <button
                onClick={() => handleDownload('html')}
                className="text-xs text-slate-ui hover:text-white hover:bg-white/5 px-2.5 py-1 transition-all"
              >
                .HTML
              </button>
            </div>
          </div>
        )}
      </div>

      {/* Content */}
      <div className="p-6 sm:p-8 max-h-[70vh] overflow-y-auto custom-scrollbar">
        <div className="prose-health prose-slate max-w-none animate-fade-in">
          <ReactMarkdown remarkPlugins={[remarkGfm]}>
            {result}
          </ReactMarkdown>
          {streaming && (
            <div className="w-1.5 h-4 bg-jade/40 inline-block ml-1 animate-pulse align-middle"></div>
          )}
        </div>
      </div>
    </div>
  )
}
